import unittest
import importlib
import json
import numpy as np
import pandas as pd

class TestFinal(unittest.TestCase):
    def test_01_ManipulateArgs(self):
        manipulate_args = asgmt.ManipulateArgs(3, 2, 7, 5, 11)
        self.assertEqual(manipulate_args.sort_asc(), [2, 3, 5, 7, 11])
        self.assertEqual(manipulate_args.sort_desc(), [11, 7, 5, 3, 2])
        self.assertEqual(manipulate_args.reverse(), [11, 5, 7, 2, 3])
        manipulate_args = asgmt.ManipulateArgs(1, 2, 3)
        self.assertEqual(manipulate_args.sort_asc(), [1, 2, 3])
        self.assertEqual(manipulate_args.sort_desc(), [3, 2, 1])
        self.assertEqual(manipulate_args.reverse(), [3, 2, 1])
    def test_02_SequenceGenerator(self):
        sequence_generator = asgmt.SequenceGenerator(5)
        self.assertEqual(sequence_generator.get_evens(), [0, 2, 4, 6, 8])
        self.assertEqual(sequence_generator.get_odds(), [1, 3, 5, 7, 9])
        sequence_generator = asgmt.SequenceGenerator(7)
        self.assertEqual(sequence_generator.get_evens(), [0, 2, 4, 6, 8, 10, 12])
        self.assertEqual(sequence_generator.get_odds(), [1, 3, 5, 7, 9, 11, 13])
        sequence_generator = asgmt.SequenceGenerator(3)
        self.assertEqual(sequence_generator.get_evens(), [0, 2, 4])
        self.assertEqual(sequence_generator.get_odds(), [1, 3, 5])
    def test_03_get_primes(self):
        self.assertEqual(asgmt.get_primes(3), [2, 3, 5])
        self.assertEqual(asgmt.get_primes(5), [2, 3, 5, 7, 11])
        self.assertEqual(asgmt.get_primes(7), [2, 3, 5, 7, 11, 13, 17])
        self.assertEqual(asgmt.get_primes(8), [2, 3, 5, 7, 11, 13, 17, 19])
        self.assertEqual(asgmt.get_primes(9), [2, 3, 5, 7, 11, 13, 17, 19, 23])
    def test_04_get_fibonacci(self):
        self.assertEqual(asgmt.get_fibonacci(3), [0, 1, 1])
        self.assertEqual(asgmt.get_fibonacci(5), [0, 1, 1, 2, 3])
        self.assertEqual(asgmt.get_fibonacci(7), [0, 1, 1, 2, 3, 5, 8])
        self.assertEqual(asgmt.get_fibonacci(8), [0, 1, 1, 2, 3, 5, 8, 13])
        self.assertEqual(asgmt.get_fibonacci(9), [0, 1, 1, 2, 3, 5, 8, 13, 21])
    def test_05_AdvancedSequenceGenerator(self):
        sequence_generator = asgmt.AdvancedSequenceGenerator(5)
        self.assertEqual(sequence_generator.get_evens(), [0, 2, 4, 6, 8])
        self.assertEqual(sequence_generator.get_odds(), [1, 3, 5, 7, 9])
        self.assertEqual(sequence_generator.get_primes(), [2, 3, 5, 7, 11])
        self.assertEqual(sequence_generator.get_fibonacci(), [0, 1, 1, 2, 3])
        sequence_generator = asgmt.AdvancedSequenceGenerator(7)
        self.assertEqual(sequence_generator.get_evens(), [0, 2, 4, 6, 8, 10, 12])
        self.assertEqual(sequence_generator.get_odds(), [1, 3, 5, 7, 9, 11, 13])
        self.assertEqual(sequence_generator.get_primes(), [2, 3, 5, 7, 11, 13, 17])
        self.assertEqual(sequence_generator.get_fibonacci(), [0, 1, 1, 2, 3, 5, 8])
        sequence_generator = asgmt.AdvancedSequenceGenerator(3)
        self.assertEqual(sequence_generator.get_evens(), [0, 2, 4])
        self.assertEqual(sequence_generator.get_odds(), [1, 3, 5])
        self.assertEqual(sequence_generator.get_primes(), [2, 3, 5])
        self.assertEqual(sequence_generator.get_fibonacci(), [0, 1, 1])
    def test_06_KeyValueMethods(self):
        key_value_methods = asgmt.KeyValueMethods(twn="Taiwan")
        self.assertEqual(key_value_methods.reverse(), {'Taiwan': 'twn'})
        self.assertEqual(key_value_methods.to_upper(), {'TWN': 'TAIWAN'})
        self.assertEqual(key_value_methods.to_lower(), {'twn': 'taiwan'})
        key_value_methods = asgmt.KeyValueMethods(twn="Taiwan", jpn="Japan")
        self.assertEqual(key_value_methods.reverse(), {'Taiwan': 'twn', 'Japan': 'jpn'})
        self.assertEqual(key_value_methods.to_upper(), {'TWN': 'TAIWAN', 'JPN': 'JAPAN'})
        self.assertEqual(key_value_methods.to_lower(), {'twn': 'taiwan', 'jpn': 'japan'})
    def test_07_rotate_character(self):
        self.assertEqual(asgmt.rotate_character("A"), 'N')
        self.assertEqual(asgmt.rotate_character("B"), 'O')
        self.assertEqual(asgmt.rotate_character("L"), 'Y')
        self.assertEqual(asgmt.rotate_character("M"), 'Z')
        self.assertEqual(asgmt.rotate_character("a"), 'n')
        self.assertEqual(asgmt.rotate_character("b"), 'o')
        self.assertEqual(asgmt.rotate_character("l"), 'y')
        self.assertEqual(asgmt.rotate_character("m"), 'z')
        self.assertEqual(asgmt.rotate_character("N"), 'A')
        self.assertEqual(asgmt.rotate_character("O"), 'B')
        self.assertEqual(asgmt.rotate_character("Y"), 'L')
        self.assertEqual(asgmt.rotate_character("Z"), 'M')
        self.assertEqual(asgmt.rotate_character("n"), 'a')
        self.assertEqual(asgmt.rotate_character("o"), 'b')
        self.assertEqual(asgmt.rotate_character("y"), 'l')
        self.assertEqual(asgmt.rotate_character("z"), 'm')
    def test_08_rotate_sentence(self):
        self.assertEqual(asgmt.rotate_sentence("Abj vf orggre guna arire."), 'Now is better than never.')
        self.assertEqual(asgmt.rotate_sentence("Now is better than never."), 'Abj vf orggre guna arire.')
        self.assertEqual(asgmt.rotate_sentence("Rkcyvpvg vf orggre guna vzcyvpvg."), 'Explicit is better than implicit.')
        self.assertEqual(asgmt.rotate_sentence("Explicit is better than implicit."), 'Rkcyvpvg vf orggre guna vzcyvpvg.')
    def test_09_Rot13(self):
        rot13 = asgmt.Rot13()
        self.assertEqual(rot13.rotate_character("A"), 'N')
        self.assertEqual(rot13.rotate_character("B"), 'O')
        self.assertEqual(rot13.rotate_character("L"), 'Y')
        self.assertEqual(rot13.rotate_character("M"), 'Z')
        self.assertEqual(rot13.rotate_character("a"), 'n')
        self.assertEqual(rot13.rotate_character("b"), 'o')
        self.assertEqual(rot13.rotate_character("l"), 'y')
        self.assertEqual(rot13.rotate_character("m"), 'z')
        self.assertEqual(rot13.rotate_sentence("Abj vf orggre guna arire."),
                         "Now is better than never.")
        self.assertEqual(rot13.rotate_sentence("Now is better than never."),
                         "Abj vf orggre guna arire.")
        self.assertEqual(rot13.rotate_sentence("Rkcyvpvg vf orggre guna vzcyvpvg."),
                         "Explicit is better than implicit.")
        self.assertEqual(rot13.rotate_sentence("Explicit is better than implicit."),
                         "Rkcyvpvg vf orggre guna vzcyvpvg.")
    def test_10_Friends(self):
        friends = asgmt.Friends()
        self.assertEqual(friends.get_actor("Rachel Green"), 'Jennifer Aniston')
        self.assertEqual(friends.get_actor("Monica Geller"), 'Courteney Cox')
        self.assertEqual(friends.get_actor("Phoebe Buffay"), 'Lisa Kudrow')
        self.assertEqual(friends.get_character("Jennifer Aniston"), 'Rachel Green')
        self.assertEqual(friends.get_character("Courteney Cox"), 'Monica Geller')
        self.assertEqual(friends.get_character("Lisa Kudrow"), 'Phoebe Buffay')
        self.assertEqual(friends.get_actor("Joey Tribbiani"), 'Matt LeBlanc')
        self.assertEqual(friends.get_actor("Chandler Bing"), 'Matthew Perry')
        self.assertEqual(friends.get_actor("Ross Geller"), 'David Schwimmer')
        self.assertEqual(friends.get_character("Matt LeBlanc"), 'Joey Tribbiani')
        self.assertEqual(friends.get_character("Matthew Perry"), 'Chandler Bing')
        self.assertEqual(friends.get_character("David Schwimmer"), 'Ross Geller')
    def test_11_import_mlb_teams_json(self):
        mlb_teams_json = asgmt.import_mlb_teams_json()
        self.assertIsInstance(mlb_teams_json, list)
        self.assertEqual(len(mlb_teams_json), 30)
    def test_12_find_location_with_name(self):
        self.assertEqual(asgmt.find_location_with_name("New York Yankees"), 'Bronx')
        self.assertEqual(asgmt.find_location_with_name("New York Mets"), 'Flushing')
        self.assertEqual(asgmt.find_location_with_name("Los Angeles Dodgers"), 'Los Angeles')
        self.assertEqual(asgmt.find_location_with_name("Kansas City Royals"), 'Kansas City')
    def test_13_find_names_with_franchise(self):
        self.assertEqual(asgmt.find_names_with_franchise("Los Angeles"), ('Los Angeles Angels', 'Los Angeles Dodgers'))
        self.assertEqual(asgmt.find_names_with_franchise("New York"), ('New York Yankees', 'New York Mets'))
        self.assertEqual(asgmt.find_names_with_franchise("Boston"), 'Boston Red Sox')
        self.assertEqual(asgmt.find_names_with_franchise("Chicago"), ('Chicago White Sox', 'Chicago Cubs'))
        self.assertEqual(asgmt.find_names_with_franchise("San Francisco"), 'San Francisco Giants')
    def test_14_import_imdb_files(self):
        movies, movies_directors, directors = asgmt.import_imdb_files()
        self.assertEqual(movies.shape, (250, 5))
        self.assertEqual(movies_directors.shape, (284, 4))
        self.assertEqual(directors.shape, (179, 3))
    def test_15_merge_dataframes(self):
        merged_dataframe = asgmt.merge_dataframes()
        self.assertEqual(merged_dataframe.shape, (284, 3))
        self.assertIn("The Shawshank Redemption", merged_dataframe["title"].values)
        self.assertIn("The Green Mile", merged_dataframe["title"].values)
        self.assertIn("Frank Darabont", merged_dataframe["director"].values)
        self.assertIn("Francis Ford Coppola", merged_dataframe["director"].values)
    def test_16_find_movies_directed_by_nolan_spielberg(self):
        movies_directed_by_nolan_spielberg = asgmt.find_movies_directed_by_nolan_spielberg()
        self.assertEqual(movies_directed_by_nolan_spielberg.shape, (15, 2))
        self.assertIn("Interstellar", movies_directed_by_nolan_spielberg["title"].values)
        self.assertIn("The Dark Knight", movies_directed_by_nolan_spielberg["title"].values)
        self.assertIn("Jurassic Park", movies_directed_by_nolan_spielberg["title"].values)
        self.assertIn("Catch Me If You Can", movies_directed_by_nolan_spielberg["title"].values)
    def test_17_find_movies_with_multiple_directors(self):
        movies_with_multiple_directors = asgmt.find_movies_with_multiple_directors()
        self.assertEqual(movies_with_multiple_directors.shape, (60, 3))
        self.assertIn("Avengers: Endgame", movies_with_multiple_directors["title"].values)
        self.assertIn("Avengers: Infinity War", movies_with_multiple_directors["title"].values)
        self.assertIn("Anthony Russo", movies_with_multiple_directors["director"].values)
        self.assertIn("Joe Russo", movies_with_multiple_directors["director"].values)
    def test_18_import_premier12_files(self):
        stats_batting, stats_pitching = asgmt.import_premier12_files()
        self.assertEqual(stats_batting.shape, (164, 18))
        self.assertEqual(stats_pitching.shape, (166, 28))
    def test_19_find_batting_leaders(self):
        batting_leaders = asgmt.find_batting_leaders()
        self.assertEqual(batting_leaders.shape, (4, 5))
        self.assertIn("CHEN, Chieh-Hsien", batting_leaders["Player"].values)
    def test_20_find_pitching_leaders(self):
        pitching_leaders = asgmt.find_pitching_leaders()
        self.assertEqual(pitching_leaders.shape, (33, 4))
        self.assertIn("CHANG, Yi", pitching_leaders["Player"].values)
        self.assertIn("HILL, Rich", pitching_leaders["Player"].values)
        self.assertIn("FUJIHIRA, Shoma", pitching_leaders["Player"].values)

asgmt = importlib.import_module("asgmt")
suite = unittest.TestLoader().loadTestsFromTestCase(TestFinal)
runner = unittest.TextTestRunner(verbosity=2)
test_results = runner.run(suite)
number_of_failures = len(test_results.failures)
number_of_errors = len(test_results.errors)
number_of_test_runs = test_results.testsRun
number_of_successes = number_of_test_runs - (number_of_failures + number_of_errors)
print("You've got {} successes among {} questions.".format(number_of_successes, number_of_test_runs))